# Configuration PlayerShops avec système de zones
# Plugin de shops joueur basé sur la détection automatique de zones de beacons

# Paramètres généraux
settings:
  # Configuration du monde
  world:
    market_world: "Market"           # Nom du monde contenant les shops
    auto_create_shops: true          # Créer automatiquement des shops depuis les zones détectées
    auto_scan_on_startup: true       # Scanner le monde au démarrage du serveur

  # Configuration de la location
  rent:
    price: 1000                      # Prix de base en beacons
    duration: 259200000              # Durée en millisecondes (3 jours)
    grace_duration: 86400000         # Période de grâce en millisecondes (1 jour)

  # Configuration de la personnalisation
  customization:
    custom-message:
      price: 100                     # Prix pour un message personnalisé
      cooldown: 5000                 # Cooldown entre messages en millisecondes (5 secondes)
    floating-text:
      price: 50                      # Prix par texte flottant
      max-per-shop: 3                # Maximum de textes flottants par shop
    npc:
      price: 500                     # Prix pour un PNJ

  # Configuration des annonces
  advertisement:
    boost:
      price: 200                     # Prix pour booster une annonce
      duration: 3600000              # Durée du boost en millisecondes (1 heure)

  # Configuration des zones
  zones:
    scan_radius: 300                 # Rayon de scan pour les beacons (blocs)
    min_beacons: 1                   # Minimum de beacons pour créer une zone
    max_beacons: 100                  # Maximum de beacons par zone
    zone_height_below: 1             # Blocs en dessous des beacons inclus dans la zone
    zone_height_above: 20            # Blocs au-dessus des beacons inclus dans la zone

  # Configuration des sauvegardes
  backup:
    auto_backup_on_expire: true      # Sauvegarder automatiquement quand un shop expire
    compression_enabled: true        # Activer la compression des sauvegardes
    market_backup_enabled: true      # Activer les sauvegardes spéciales pour les market zones

# Messages du plugin
messages:
  prefix: "§6§lSHOP §8»"

  # Messages d'erreur
  errors:
    no-permission: "§cVous n'avez pas la permission!"
    player-only: "§cCette commande ne peut être utilisée que par un joueur!"
    shop-not-found: "§cShop introuvable!"
    zone-not-found: "§cZone introuvable!"
    already-rented: "§cCe shop est déjà loué!"
    no-shop: "§cVous ne possédez aucun shop!"
    not-enough-beacons: "§cVous n'avez pas assez de beacons!"
    transaction-failed: "§cErreur lors de la transaction!"
    player-not-found: "§cJoueur introuvable!"
    already-member: "§cCe joueur est déjà membre!"
    not-member: "§cCe joueur n'est pas membre!"
    invalid-price: "§cPrix invalide!"
    chest-shop-exists: "§cCe coffre a déjà un chest shop!"
    no-space-sign: "§cPas de place pour placer un panneau!"
    inventory-full: "§cVotre inventaire est plein!"
    insufficient-stock: "§cStock insuffisant!"
    one-beacon-only: "§cVous ne pouvez avoir qu'un seul beacon!"
    legendary-pickaxe: "§cVous ne pouvez pas vendre une pioche légendaire!"
    not-in-shop: "§cVous devez être dans un shop pour le revendiquer!"
    shop-unavailable: "§cCe shop n'est pas disponible!"
    max-floating-texts: "§cVous avez atteint la limite de textes flottants! (3 max)"
    grace-period: "§cCe shop est en période de grâce!"
    zone-unavailable: "§cCette zone n'est pas disponible!"
    no-zones-found: "§cAucune zone trouvée dans ce monde!"
    scan-in-progress: "§cUn scan est déjà en cours!"

  # Messages de succès
  success:
    shop-claimed: "§aVous avez revendiqué le shop {shop} pour {price} beacons!"
    shop-extended: "§aVotre shop a été prolongé de 3 jours!"
    member-added: "§a{player} a été ajouté à votre shop!"
    member-removed: "§a{player} a été retiré de votre shop!"
    custom-message-set: "§aMessage d'approche défini!"
    custom-message-removed: "§aMessage personnalisé supprimé!"
    floating-text-added: "§aTexte flottant ajouté à votre position!"
    floating-text-removed: "§aTexte flottant supprimé!"
    npc-added: "§aPNJ {name} ajouté!"
    npc-removed: "§aPNJ supprimé!"
    chest-shop-created: "§aChest shop de {mode} créé avec succès!"
    chest-shop-removed: "§aChest shop supprimé!"
    price-updated: "§aPrix modifié: {price} beacons"
    mode-switched: "§aMode changé en {mode}!"
    advertisement-created: "§aAnnonce créée!"
    advertisement-boosted: "§aAnnonce boostée pour 1 heure!"
    purchase-success: "§aAchat effectué! ({price} beacons)"
    sell-success: "§aVente effectuée! (+{price} beacons)"
    zones-scanned: "§aScan terminé! {zones} zones créées depuis {beacons} beacons."
    backup-created: "§aSauvegarde créée pour la zone {zone}!"
    backup-restored: "§aZone {zone} restaurée depuis la sauvegarde!"

  # Messages d'information
  info:
    merchant-discount: "§eRéduction commerçant niveau 5+ appliquée!"
    rent-expired: "§cVotre shop {shop} a expiré!"
    grace-period-started: "§eVotre shop {shop} est entré en période de grâce!"
    grace-period-warning: "§eVous avez 24h pour prolonger avant la fermeture définitive."
    shop-closed: "§cVotre shop {shop} a été fermé définitivement!"
    sale-notification: "§a{player} a acheté dans votre chest shop! (+{price} beacons)"
    purchase-notification: "§a{player} a vendu dans votre chest shop! (-{price} beacons)"
    approach-message: "§6§lSHOP §8» {message}"
    floating-text-list: "§6Vos textes flottants:"
    chest-shop-info: "§6Informations sur votre chest shop ({mode}):"
    modify-hint: "§7Clic gauche pour modifier le prix/mode"
    scan-progress: "§7Scan en cours... {progress}% terminé"
    teleport-available: "§aTéléportation directe disponible pour ce shop!"
    zone-info: "§7Cette zone contient {beacons} beacons et {blocks} blocs."

# Configuration des téléportations
teleportation:
  enable_zone_teleports: true        # Activer les téléportations directes aux zones
  teleport_safety_check: true       # Vérifier la sécurité des téléportations
  teleport_delay: 0                  # Délai avant téléportation (secondes)

# Configuration des permissions étendues
permissions:
  zone-management:
    scan-worlds: "playershops.admin.scan"
    backup-zones: "playershops.admin.backup"
    restore-zones: "playershops.admin.restore"
  advanced-features:
    unlimited-floating-texts: "playershops.vip.unlimited"
    free-customization: "playershops.vip.free"
    priority-teleport: "playershops.vip.teleport"